### ISSUE TITLE
Helper tests don't properly pull in Rails dependencies

### ISSUE THREAD

**Issue by kaidamasaki** [blowmage/minitest-rails#221] opened 2019-10-23 23:04 UTC
Code like this fails to pull in things like built in view helpers:

```ruby
describe ApplicationHelper do
  describe 'readable_date' do
```

Code like this works, though:
```ruby
describe ApplicationHelper, :helper do
  describe 'readable_date' do
```

It would be great if the latter was documented in the README or the former was supported.

**Comment by blowmage** [comment] 2019-10-24 15:28
The problem is that there is no good way to determine which modules are helpers. There is no common ancestry, and there is no bulletproof naming conventions.

If you choose to make Minitest use `ActionView::TestCase` for all modules, even ones in your application that are not helpers, you can add the following to your test helper:

```ruby
class ActionView::TestCase
  # Use AS::TC for the base class when describing a helper
  register_spec_type(self) do |desc|
    Module === desc && !(Class === desc)
  end
end
```

Or, if you choose to make Minitest use `ActionView::TestCase` for all modules that end in "Helper", you can add the following to your test helper:

```ruby
class ActionView::TestCase
  # Use AS::TC for the base class when describing a helper
  register_spec_type(self) do |desc|
    Module === desc && !(Class === desc) && desc.class.to_s.match /Helper$/
  end
end
```

**Comment by blowmage** [comment] 2019-10-24 17:26
You can try something like this:

```ruby
class ActionView::TestCase
  # Use AS::TC for the base class when describing a helper
  register_spec_type(self) do |desc|
    Module === desc && !(Class === desc) &&  desc.class.instance_methods(false).any? { |m| desc.class.instance_method(m).source_location.first.to_s.include? Rails.root.join("app", "helpers").to_s }
  end
end
```

**Comment by blowmage** [comment] 2019-11-21 16:28
I am not inclined to add the lookup from my previous comment to this gem. And I haven't seen any other requests for this. So I am going to close this issue.

If anyone can offer a justification for this please open a new issue linking to this issue.

**Closed by blowmage** 2019-11-21 16:28 UTC
